Back_End/ToDoList/ToDoList/Models/Assignment.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ToDoList.Models;

public partial class Assignment
{
    [Key]
    public int AssignmentId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string AssignedTo { get; set; }

    [InverseProperty("Assignment")]
    public virtual ICollection<ToDoTask> ToDoTasks { get; set; } = new List<ToDoTask>();
}

Back_End/ToDoList/ToDoList/Models/ErrorViewModel.cs
namespace ToDoList.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Back_End/ToDoList/ToDoList/Models/ToDoTask.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ToDoList.Models;

public partial class ToDoTask
{
    [Key]
    public int TaskId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedOn { get; set; }

    public bool Done { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Description { get; set; }

    public int AssignmentId { get; set; }

    [ForeignKey("AssignmentId")]
    [InverseProperty("ToDoTasks")]
    public virtual Assignment Assignment { get; set; }
}

Back_End/ToDoList/ToDoList/Models/ToDoTaskContext.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ToDoList.Models;

public partial class ToDoTaskContext : DbContext
{
    public ToDoTaskContext()
    {
    }

    public ToDoTaskContext(DbContextOptions<ToDoTaskContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Assignment> Assignments { get; set; }

    public virtual DbSet<ToDoTask> ToDoTasks { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-F153P9A\\SQLEXPRESS;Initial Catalog=ToDoTask;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Assignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("PK__Assignme__32499E772348A98C");
        });

        modelBuilder.Entity<ToDoTask>(entity =>
        {
            entity.HasKey(e => e.TaskId).HasName("PK__ToDoTask__7C6949B10E3B70F5");

            entity.HasOne(d => d.Assignment).WithMany(p => p.ToDoTasks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ToDoTasks_Assignments");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

Back_End/ToDoList/ToDoList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Back_End/ToDoList/ToDoList/Controllers/ToDoTaskController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;
using ToDoList.Service;

namespace ToDoList.Controllers
{
    public class ToDoTaskController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            List<ToDoTask> tasks = new List<ToDoTask>();

            using (ToDoListService toDoListService = new ToDoListService())
            {
                tasks = toDoListService.GetAllTasks();
            }

            return View(tasks);

        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(ToDoTask task)
        {
            if (task == null)
            {
                return BadRequest();
            }
            ToDoTask taskToAdd = new ToDoTask();
            taskToAdd.Name = task.Name;
            taskToAdd.CreatedOn = task.CreatedOn;
            taskToAdd.Description = task.Description;
            taskToAdd.Done = false;
            taskToAdd.Assignment = task.Assignment;

            using (ToDoListService toDoListService = new ToDoListService())
            {
                toDoListService.CreateToDoTask((taskToAdd));
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ToDoTask taskToEdit;
            using (ToDoListService toDoListService = new ToDoListService())
            {
                taskToEdit = toDoListService.GetToDoTask(id);
            }

            if (taskToEdit == null)
            {
                return NotFound();
            }

            return View(taskToEdit);

        }
        [HttpPost]
        public IActionResult Edit(ToDoTask task)
        {
            if (task == null)
            {
                return BadRequest();
            }

            bool result = false;
            using (ToDoListService toDoListService = new ToDoListService())
            {
                result = toDoListService.TryEditTask(task);
            }
            if (result)
            {
                return RedirectToAction("Index");
            }

            return BadRequest();
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            ToDoTask taskToDetails = new ToDoTask();
            using (ToDoListService toDoListService = new ToDoListService())
            {
                taskToDetails = toDoListService.GetToDoTask(id);
            }
            if (taskToDetails == null)
            {
                return NotFound();
            }
            return View(taskToDetails);
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            using (ToDoListService toDoListService = new ToDoListService())
            {
                try
                {
                    toDoListService.DeleteTask(id);
                }
                catch (InvalidOperationException e)
                {
                    return NotFound(e);
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Back_End/ToDoList/ToDoList/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Back_End/ToDoList/ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoTask" asp-action="Index">ToDoTask</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ToDoList - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Back_End/ToDoList/ToDoList/Views/ToDoTask/Create.cshtml
@model ToDoList.Models.ToDoTask

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label"></label>
                <input asp-for="CreatedOn" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Assignment.CreatedBy" class="control-label"></label>
                <input asp-for="Assignment.CreatedBy" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Assignment.AssignedTo" class="control-label"></label>
                <input asp-for="Assignment.AssignedTo" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Back_End/ToDoList/ToDoList/Views/ToDoTask/Details.cshtml
@model ToDoList.Models.ToDoTask

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<h4>ToDoTask</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <p>@Model.Name</p>
            </div>
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label"></label>
                <p>@Model.CreatedOn.ToString("yyyy-MM-ddTHH:mm")</p>
            </div>
            <div class="form-group">
                <label asp-for="Done" class="control-label"></label>
                <p>@Model.Done</p>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <p>@Model.Description</p>
            </div>
            <div class="form-group">
                <label asp-for="Assignment.CreatedBy" class="control-label"></label>
                <p>@Model.Assignment.CreatedBy</p>
            </div>
            <div class="form-group">
                <label asp-for="Assignment.AssignedTo" class="control-label"></label>
                <p>@Model.Assignment.AssignedTo</p>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Back_End/ToDoList/ToDoList/Views/ToDoTask/Edit.cshtml
@model ToDoList.Models.ToDoTask

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ToDoTask</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <input type="hidden" asp-for="TaskId"/>
                <input type="hidden" asp-for="AssignmentId"/>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="CreatedOn" class="control-label"></label>
                <input asp-for="CreatedOn" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Done" class="control-label"></label>
                <input asp-for="Done" type="checkbox"/>
            </div>
            <div class="form-group">
                <label asp-for="Assignment.CreatedBy" class="control-label"></label>
                <input asp-for="Assignment.CreatedBy" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Assignment.AssignedTo" class="control-label"></label>
                <input asp-for="Assignment.AssignedTo" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Back_End/ToDoList/ToDoList/Views/ToDoTask/Index.cshtml
@model IEnumerable<ToDoTask>
@{
}

<h1>ToDoList</h1>

<p>
    @Html.ActionLink("Create a new task", "Create")
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TaskId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Assignment.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Assignment.AssignedTo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Done)
        </th>
    </tr>
    </thead>
    <tbody>
    @if (Model.Count() <= 0)
    {
        <tr>
                <td colspan="7"> There is no data in the database!</td>
        </tr>
    }
    else
    {
    @foreach (var task in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => task.TaskId)
            </td>
            <td>
                @Html.DisplayFor(modelItem =>task.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => task.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => task.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => task.Assignment.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => task.Assignment.AssignedTo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => task.Done)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=task.TaskId })
                @Html.ActionLink("Details","Details", new {id = task.TaskId})
                @Html.ActionLink("Delete", "Delete", new {id=task.TaskId})
            </td>

        </tr>
    }
    }
    </tbody>
</table>